### ISSUE TITLE
Can not run tests

### ISSUE THREAD

**Issue by drbarzyk** [mixxxdj/libkeyfinder#23] opened 2022-08-26 22:58 UTC
```
╰─➤  cd build
(base) ╭─$ ~/Downloads/libkeyfinder-main/build  
╰─➤  ctest --parallel 8
Test project /Downloads/libkeyfinder-main/build
    Start 1: keyfinder-tests_NOT_BUILT-b12d07c
Could not find executable keyfinder-tests_NOT_BUILT-b12d07c
Looked in the following places:
keyfinder-tests_NOT_BUILT-b12d07c
keyfinder-tests_NOT_BUILT-b12d07c
Release/keyfinder-tests_NOT_BUILT-b12d07c
Release/keyfinder-tests_NOT_BUILT-b12d07c
Debug/keyfinder-tests_NOT_BUILT-b12d07c
Debug/keyfinder-tests_NOT_BUILT-b12d07c
MinSizeRel/keyfinder-tests_NOT_BUILT-b12d07c
MinSizeRel/keyfinder-tests_NOT_BUILT-b12d07c
RelWithDebInfo/keyfinder-tests_NOT_BUILT-b12d07c
RelWithDebInfo/keyfinder-tests_NOT_BUILT-b12d07c
Deployment/keyfinder-tests_NOT_BUILT-b12d07c
Deployment/keyfinder-tests_NOT_BUILT-b12d07c
Development/keyfinder-tests_NOT_BUILT-b12d07c
Development/keyfinder-tests_NOT_BUILT-b12d07c
Unable to find executable: keyfinder-tests_NOT_BUILT-b12d07c
1/1 Test #1: keyfinder-tests_NOT_BUILT-b12d07c ...***Not Run   0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.00 sec

The following tests FAILED:
	  1 - keyfinder-tests_NOT_BUILT-b12d07c (Not Run)
Errors while running CTest
Output from these tests are in: /Downloads/libkeyfinder-main/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

**~/Downloads/libkeyfinder-main/build/tests:**
```
(base) ╭─$ ~/Downloads/libkeyfinder-main/build/tests  
╰─➤  ls
CMakeFiles                            Makefile                              cmake_install.cmake
CTestTestfile.cmake                   Testing                               keyfinder-tests_include-b12d07c.cmake
```

**keyfinder-tests_include-b12d07c.cmake:**
```
if(EXISTS "~/Downloads/libkeyfinder-main/build/tests/keyfinder-tests_tests-b12d07c.cmake")
  include("~/Downloads/libkeyfinder-main/build/tests/keyfinder-tests_tests-b12d07c.cmake")
else()
  add_test(keyfinder-tests_NOT_BUILT-b12d07c keyfinder-tests_NOT_BUILT-b12d07c)
endif()
```

Seems like I am looking for _**keyfinder-tests_tests-b12d07c.cmake**_ but it is nowhere.

**Comment by Be-ing** [comment] 2022-08-27 18:40
Duplicate of #22?

**Closed** 2023-09-27 23:27 UTC
